# Version S41

#########################################################################################################
### PLEASE NOTE:                                                                                      ###
### This file and .gitlab folder are managed by pipeline-template.                                    ###
### Don't make changes here - they will be overwritten.                                               ###
#########################################################################################################

# Gitlab Cache Settings
cache:
  untracked: false
  paths:
    - "sbt-cache"

stages:
  - BUILD
  - QA
  - STASH
  - DEPLOY
  - DEPLOY-1
  - QA-POST
  - DEPLOY-2

build:
  stage: BUILD
  artifacts:
    expire_in: '1 day'
    paths:
      - "target"
      - "project"
  script:
    - .gitlab/S-BUILD-build.sh
  tags:
    - sce-v2

unit-test:
  stage: QA
  artifacts:
    expire_in: '1 day'
    paths:
      - "target/scala-2.12/test-classes"
      - "target/scala-2.12/coverage-report"
      - "target/scala-2.12/scoverage-report"
  script:
    - .gitlab/S-QA-unit-test.sh
  tags:
    - sce-v2

man-foss-analys:
  stage: QA
  cache:
    paths:
      - "sbt-cache"
    policy: pull
  dependencies:
    - build
  except:
    - tags
  script:
    - .gitlab/S-QA-man-foss-analys.sh
  tags:
    - sce-v2
  when:
    manual

foss-analysis:
  stage: QA
  cache:
    paths:
      - "sbt-cache"
    policy: pull
  dependencies:
    - build
  only:
    - tags
  script:
    - .gitlab/S-QA-foss-analysis.sh
  tags:
    - sce-v2

jar-push:
  stage: STASH
  cache:
    paths:
      - "sbt-cache"
    policy: pull
  dependencies:
    - build
  only:
    - tags
  script:
    - .gitlab/S-STASH-jar-push.sh
  tags:
    - sce-v2

image-push:
  stage: STASH
  cache: {}
  dependencies:
    - build
  image:
    name: registry.hub.docker.com/griffinplus/gitlab-kaniko
  only:
    - tags
  script:
    - .gitlab/S-STASH-image-push.sh
  tags:
    - sce-v2
  timeout: 3m

man-image-push:
  stage: STASH
  cache: {}
  dependencies:
    - build
  except:
    - tags
  image:
    name: registry.hub.docker.com/griffinplus/gitlab-kaniko
  script:
    - .gitlab/S-STASH-man-image-push.sh
  tags:
    - sce-v2
  timeout: 3m
  when:
    manual

man-dev-deploy:
  stage: DEPLOY
  cache: {}
  dependencies: []
  except:
    - tags
  script:
    - .gitlab/S-DEPLOY-man-dev-deploy.sh
  tags:
    - sce-v2
  when:
    manual

dev-deploy:
  stage: DEPLOY-1
  cache: {}
  only:
    - tags
  script:
    - .gitlab/S-DEPLOY-1-dev-deploy.sh
  tags:
    - sce-v2

int-test:
  stage: QA-POST
  only:
    - tags
  script:
    - .gitlab/S-QA-POST-int-test.sh
  tags:
    - sce-v2

foss-report:
  stage: QA-POST
  cache:
    paths:
      - "sbt-cache"
    policy: pull
  only:
    - tags
  script:
    - .gitlab/S-QA-POST-foss-report.sh
  tags:
    - sce-v2

apidoc-release:
  stage: QA-POST
  cache: {}
  only:
    - tags
  script:
    - .gitlab/S-QA-POST-apidoc-release.sh
  tags:
    - sce-v2

man-demo-deploy:
  stage: DEPLOY-2
  cache: {}
  only:
    - tags
  script:
    - .gitlab/S-DEPLOY-2-man-demo-deploy.sh
  tags:
    - sce-v2
  when:
    manual
